### PR TITLE
PRODUCTS-1216 Avoid multiple includes/executions of settings.js

### PR DESCRIPTION
**Pull request by ataraxie**
...by checking for existence of a (hidden) global __SF__ object

### CODE REVIEW

**Comment by ataraxie** [comment]
@KappaNossi @sschatter @Pyrazol I think I have already fixed everything else associated with this issue (PRODUCTS-1216, PRODUCTS-1266). If you approve this I will create a new release (0.5.2) and then create a PR in TeamAdmin and LivelyTheme.

@Pyrazol I will let you know the solution to PRODUCTS-1266 once I created the release.

**Review by sschatter — APPROVED** [review]

**Comment by vicox** [comment]
The root problem is that all apps use the same context "settings". This is why settings.js will be included multiple times in the same page. I would instruct in the README to use a different context in every app. Like: <context>MyExampleApp-settings</context> and #requireResourcesForContext("MyExampleApp-settings"). Your solution only works if all apps use the same version of the settings-framework. But if one uses a lower version and sets __SF__ first, then the one that wants to use a higher version is screwed.

**Comment by ataraxie** [comment]
That's right. I didn't realize the thing with the context. With my version, the last included script "wins" which is certainly not perfect. Your solution is the better option. Didn't think it's that easy!

**Comment by ataraxie** [comment]
Actually didn't want to close this. Georg's approach is important but this is a good safety mechanism to not break things!

**Comment by ataraxie** [comment]
Updated README. By the way. The issue ID is actually PRODUCTS-1215 and not PRODUCTS-1216. Sorry for the confusion.

**Review by Pyrazol — APPROVED** [review]
Nice!

**Pull request merged**
